import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en' | 'ar';
  setLanguage: (lang: 'en' | 'ar') => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// English translations
const en = {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.expertise': 'Expertise',
    'nav.clients': 'Clients',
    'nav.career': 'Careers',
    'nav.media': 'Media',
    'nav.library': 'Library',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact Us',
    
    // Hero
    'hero.title': 'Shebab Law Firm',
    'hero.title.primary': 'Shebab',
    'hero.title.secondary': 'Law Firm',
    'hero.subtitle': 'Your trusted legal partner',
    'hero.description': 'An Egyptian law firm bringing together highly qualified legal professionals with diverse local and international backgrounds, delivering innovative solutions across multiple sectors.',
    'hero.cta': 'Learn More About Us',
    'hero.cta.secondary': 'Schedule Consultation',
    'hero.stats.years': 'Years Experience',
    'hero.stats.cases': 'Cases Won',
    'hero.stats.clients': 'Clients Served',
    'hero.stats.success': 'Success Rate',
    
    // About Preview
    'about.title': 'About Our Firm',
    'about.description': 'Shebab Law Firm is an Egyptian law firm that brings together highly qualified legal professionals with diverse local and international backgrounds, delivering innovative solutions across multiple sectors.',
    'about.cta': 'Learn More',
    'about.p1': 'Shehab & El Awamy is an Egyptian law firm that brings together highly qualified legal professionals with diverse local and international backgrounds. Founded to provide both legal services and consultancy, we employ innovative methods to keep pace with the evolving governmental and legal landscape.',
    'about.p2': 'We are fully attuned to the daily challenges faced by corporations and are committed to delivering swift, strategic business solutions. Our lawyers work closely with clients, building trust, commitment, and loyalty by offering innovative solutions that drive success across multiple sectors including Banking, Oil and Gas, Heavy Industries, Healthcare, Information Technology, Communications, and Media.',
    'about.stats.years': 'Years',
    'about.stats.cases': 'Cases',
    
    // Expertise
    'expertise.title': 'Areas of Practice',
    'expertise.subtitle': 'Comprehensive legal services across multiple practice areas',
    'expertise.learnMore': 'Learn More',
    'expertise.cta.title': 'Need Legal Assistance?',
    'expertise.cta.text': 'Our experienced legal team is ready to help you navigate complex legal challenges and achieve the best possible outcomes.',
    'expertise.cta.schedule': 'Schedule Consultation',
    'expertise.cta.contact': 'Contact Our Team',

    // Expertise areas
    'expertise.dispute.title': 'Dispute Resolution',
    'expertise.dispute.desc': 'Comprehensive litigation services covering civil, commercial, and criminal cases with expertise in Egyptian courts.',
    'expertise.dispute.f1': 'Civil & Commercial Litigation',
    'expertise.dispute.f2': 'Criminal Defense',
    'expertise.dispute.f3': 'Alternative Dispute Resolution',

    'expertise.corporate.title': 'Corporate & Commercial Law',
    'expertise.corporate.desc': 'Fast and customized incorporation services for all types of commercial companies in Egypt and abroad.',
    'expertise.corporate.f1': 'Company Formation',
    'expertise.corporate.f2': 'Corporate Secretarial Services',
    'expertise.corporate.f3': 'Commercial Transactions',

    'expertise.employment.title': 'Employment Law',
    'expertise.employment.desc': 'Expert advice on employment laws, contract drafting, and regulatory compliance for Egyptian labor regulations.',
    'expertise.employment.f1': 'Employment Contracts',
    'expertise.employment.f2': 'Labor Policy Development',
    'expertise.employment.f3': 'Regulatory Compliance',

    'expertise.realestate.title': 'Real Estate',
    'expertise.realestate.desc': 'Real estate registration, sale and purchase agreements, and legal advice for commercial, residential, and touristic projects.',
    'expertise.realestate.f1': 'Property Registration',
    'expertise.realestate.f2': 'Sale & Purchase Agreements',
    'expertise.realestate.f3': 'Title Verification',

    'expertise.tmt.title': 'Technology, Media & Telecommunications',
    'expertise.tmt.desc': 'Specialized services in technology, media, and telecommunications with focus on licensing and regulatory compliance.',
    'expertise.tmt.f1': 'TMT Licensing',
    'expertise.tmt.f2': 'Regulatory Compliance',
    'expertise.tmt.f3': 'E-commerce Law',

    'expertise.tax.title': 'Taxation',
    'expertise.tax.desc': 'Comprehensive tax services including dispute resolution, compliance, and financial reporting in accordance with Egyptian tax law.',
    'expertise.tax.f1': 'Tax Dispute Resolution',
    'expertise.tax.f2': 'Tax Compliance',
    'expertise.tax.f3': 'Financial Reporting',

    'expertise.mna.title': 'Capital Market & M&A',
    'expertise.mna.desc': 'Expertise in public and private mergers, acquisitions, joint ventures, and restructuring with comprehensive due diligence.',
    'expertise.mna.f1': 'M&A Transactions',
    'expertise.mna.f2': 'Due Diligence',
    'expertise.mna.f3': 'Corporate Restructuring',

    'expertise.additional.title': 'Additional Services',
    'expertise.additional.desc': 'Certified translation services, due diligence investigations, and specialized business support services.',
    'expertise.additional.f1': 'Certified Translation',
    'expertise.additional.f2': 'Due Diligence',
    'expertise.additional.f3': 'Business Licensing',

    // News
    'news.title': 'Latest News & Insights',
    'news.subtitle': 'Stay informed with the latest legal developments, industry insights, and expert analysis from our legal team.',
    'news.featured': 'Featured Article',
    'news.readFull': 'Read Full Article',
    'news.readMore': 'Read More',
    
    // Statistics
    'stats.years': 'Years in Business',
    'stats.contracts': 'Contracts Closed',
    'stats.cases': 'Court Cases Won',
    'stats.clients': 'Clients Served',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Get in touch with our legal experts',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.placeholder.name': 'Your full name',
    'contact.form.placeholder.message': 'Tell us about your legal needs...',
    
    // Clients
    'clients.title': 'Our Valued Clients',
    'clients.subtitle': 'Trusted by leading organizations across various industries',
    'clients.cta.title': 'Join Our Satisfied Clients',
    'clients.cta.description': 'Experience the difference that professional legal representation can make for your business or personal legal matters.',
    'clients.cta.become': 'Become a Client',
    'clients.cta.studies': 'View Case Studies',
    

    // Company Profile (About page long content)
    'about.profile.title': 'Company Profile – Shehab & El Awamy Law Firm',
    'about.profile.aboutTitle': 'About Shehab & El Awamy Law Firm',
    'about.profile.p1': 'Shehab & El Awamy is an Egyptian law firm that brings together highly qualified legal professionals with diverse local and international backgrounds. Our expertise spans a wide range of legal disciplines, ensuring that we meet the needs of our clients with precision and skill.',
    'about.profile.p2': 'Founded to provide both legal services and consultancy, Shehab & El Awamy employs innovative methods to keep pace with the evolving governmental and legal landscape. We are fully attuned to the daily challenges faced by corporations and are committed to delivering swift, strategic business solutions. Our lawyers work closely with clients, building trust, commitment, and loyalty by offering innovative solutions that drive success.',
    'about.profile.p3': 'Our firm operates through specialized teams covering various areas of legal practice, allowing us to deliver high-quality, reliable, and efficient legal services. We serve clients across multiple sectors, including Sports, Construction, Energy, Banking, Oil and Gas, Heavy Industries, Hospitals, Information Technology, Communications, Pharmaceuticals, Media, and Transportation.',
    'about.profile.p4': 'Shehab & El Awamy addresses our clients’ needs through a comprehensive range of services, including budget approval and issuance, tax dispute resolution, certified translation services, and obtaining all types of licenses, in line with our strategic mission.',
    'about.profile.p5': 'The success of Shehab & El Awamy is driven by the experience, dedication, and strong relationships of our team members with key judicial, administrative, and organizational authorities in Egypt.',

    // Mission / Vision / Values
    'about.mission.title': 'Our Mission',
    'about.mission.body': 'At Shehab & El Awamy, we are committed to delivering high-quality legal services through our team of skilled lawyers. Our mission is to help clients achieve exceptional business outcomes by leveraging our extensive legal expertise. We strive to meet all our clients’ needs, whether locally or internationally, and aim to be recognized as Egypt’s premier law services provider.',
    'about.vision.title': 'Our Vision',
    'about.vision.body': 'Our vision at Shehab & El Awamy is to become trusted advisors to both local and international clients. We aim to be their go-to source for authentic legal advice, offering professional negotiation techniques and achieving amicable settlements that satisfy all parties involved.',
    'about.values.title': 'Our Values',
    'about.values.body': 'We are deeply committed to our clients, driven by a thorough understanding of both local and international laws. Our goal is to exceed client expectations by providing transparent, determined, and credible legal services. We prioritize integrity, efficiency, and responsiveness in all our dealings.',

    // Services Overview
    'about.services.title': 'Our Services',
    'about.services.p1': 'We assist clients from the very start of their business journey. We provide expert consultancy on the most suitable business structure, guide them through social insurance, the Investment Organization, and the Capital Market Organization, and draft all necessary corporate contracts while identifying and mitigating potential risks.',
    'about.services.p2': 'As a full-service law firm based in Cairo, Egypt, we cater to the wide-ranging legal needs of multinational, regional, and local corporations, as well as high-net-worth individuals. We offer distinguished legal services with quantifiable reporting methods to support short-, medium-, and long-term business goals.',

    // Core Practice Areas (labels only)
    'about.practices.title': 'Core Practice Areas',
    'about.practices.list.1': 'Real Estate & Real Estate Finance',
    'about.practices.list.2': 'Technology, Media, and Telecommunications',
    'about.practices.list.3': 'Employment',
    'about.practices.list.4': 'Intellectual Property',
    'about.practices.list.5': 'Litigation',
    'about.practices.list.6': 'Capital Market, Mergers & Acquisitions',
    'about.practices.list.7': 'Corporate & Commercial',

    // Sections details
    'about.section.corporate.title': 'Corporate & Commercial',
    'about.section.corporate.body': 'Fast and customized incorporation services for all types of commercial companies in Egypt and abroad. Corporate secretarial, general advice, and support across establishment, licensing, and post-establishment matters. Drafting and advising on distribution, agency, licensing, manufacturing, supply, financing, and other operational agreements.',

    'about.section.mna.title': 'Mergers & Acquisitions',
    'about.section.mna.body': 'Public and private M&A, divestitures, joint ventures, spin-offs, restructuring, and post-acquisition integration. In-depth legal due diligence, risk assessments, remedial actions, and full documentation/negotiation support.',

    'about.section.litigation.title': 'Litigation',
    'about.section.litigation.body': 'Comprehensive litigation handling across banking and finance, commercial transactions, M&A, construction, corporate matters, investment, and telecommunications.',

    'about.section.employment.title': 'Employment',
    'about.section.employment.body': 'Advice on employment laws and regulations, drafting employment contracts, ensuring compliance, and supporting development and implementation of labor policies.',

    'about.section.tmt.title': 'Technology, Media & Telecommunications',
    'about.section.tmt.body': 'Dedicated TMT department offering licensing, regulatory compliance, intellectual property services, and advice on innovation and e-commerce.',

    'about.section.realestate.title': 'Real Estate',
    'about.section.realestate.body': 'Real estate registration, drafting sale and purchase agreements and construction agreements. Legal advice for contractors and developers for commercial, residential, and touristic projects, including title checks and ownership due diligence.',

    // Transpedia - Certified Translation Services
    'about.transpedia.title': 'Transpedia – Certified Translation Services',
    'about.transpedia.intro': 'Transpedia is a limited liability company registered with multiple foreign embassies. It specializes in general, legal, financial, medical, and technical translation and content authoring, serving individuals, companies, and governmental/legal institutions in both the public and private sectors.',
    'about.transpedia.general': 'General Translation: End-to-end general translation across domains from English to Arabic and vice versa.',
    'about.transpedia.legal': 'Legal Translation: Specialized legal translators for contracts, court documents, claims, notices, permits, powers of attorney, and other legal documents (Arabic/English).',
    'about.transpedia.financial': 'Financial Translation: Translation of audit reports, external auditor reports, commercial invoices, tenders, receivables, and financial/commercial documents, including business correspondence.',
    'about.transpedia.technical': 'Technical Translation: Translation for technical fields such as operation and maintenance, user manuals, technical catalogs, tenders, bids, and related technical reports.',
    'about.transpedia.medical': 'Medical Translation: Full medical translation services for reports, bulletins, and documents of a medical or therapeutic nature.',
    'about.transpedia.media': 'Media Translation: Translation for journalism and media, including press and media reports, event coverage, and related documents.',

    // Common UI elements
    'common.loading': 'Loading...',
    'common.loadingExperience': 'Preparing your experience',
    'common.loadingPage': 'Loading page...',
    'common.scrollDown': 'Scroll Down',
    'common.getDirections': 'Get Directions',
    'common.logoAlt': 'Shebab Law Firm Logo',
    'common.schedule': 'Schedule',
    'common.scheduleOnline': 'Schedule Online',
    'common.scheduleConsultation': 'Schedule Consultation',
    'common.scheduleNow': 'Schedule Now',
    'common.bookMeeting': 'Book a meeting with our legal experts',
    'common.emergencyHelp': 'Emergency Legal Help',
    'common.emergencyDesc': '24/7 urgent legal assistance',
    'common.callEmergency': 'Call Emergency Line',
    'common.clientPortal': 'Client Portal',
    'common.clientPortalDesc': 'Access your case information and documents',
    'common.loginPortal': 'Login to Portal',
    'common.consultation': 'Consultation',
    'common.consultationDesc': 'Schedule a free initial consultation to discuss your legal needs',

    // Office locations
    'office.main': 'Main Office',
    'office.downtown': 'Downtown Branch',
    'office.directions.main': 'Get Directions to Main Office',
    'office.directions.downtown': 'Get Directions to Downtown Branch',
    'office.address.main': 'Legal Plaza, Downtown Cairo\nCairo, Egypt\nP.O. Box 12345',
    'office.emergency': '24/7 Emergency Line',
    'office.emergencyDesc': 'Available for existing clients and urgent new matters requiring immediate legal intervention.',
    'office.accessibility': 'Metro accessible • Parking available',

    // Page Elements - General Content
    'page.ourTeam': 'Our Team',
    'page.awardsRecognition': 'Awards & Recognition',
    'page.bestLawFirm2023': 'Best Law Firm 2023',
    'page.legalExcellenceAwards': 'Legal Excellence Awards',
    'page.top50LawFirms': 'Top 50 Law Firms',
    'page.nationalLegalDirectory': 'National Legal Directory',
    'page.excellenceCorporateLaw': 'Excellence in Corporate Law',
    'page.businessLawJournal': 'Business Law Journal',
    'page.photoGalleryComingSoon': 'Photo gallery coming soon...',
    'page.videoContentComingSoon': 'Video content coming soon...',
    'page.messageSent': 'Message Sent!',
    'page.messageSentSuccess': 'Message Sent Successfully!',
    'page.messageSentThankYou': 'Thank you for contacting us. We\'ll get back to you within 24 hours.',
    'page.emergencyContact': 'Emergency Contact',
    'page.interactiveMapNote': 'Interactive map would be integrated here',

    // FAQ Page
    'faq.title': 'Frequently Asked Questions',
    'faq.general.q1': 'What types of legal services does Shebab Law Firm provide?',
    'faq.general.a1': 'We offer comprehensive legal services including corporate and commercial law, dispute resolution, employment law, real estate law, intellectual property protection, taxation, capital markets and M&A, and arbitration services. Our experienced team handles both complex business matters and individual legal needs.',
    'faq.general.q2': 'How do I schedule an initial consultation?',
    'faq.general.a2': 'You can schedule a consultation by calling our office, using our online contact form, or sending an email. We typically offer a 30-minute initial consultation to discuss your legal needs and determine how we can best assist you.',
    'faq.general.q3': 'Do you offer free consultations?',
    'faq.general.a3': 'Yes, we provide free initial consultations for most practice areas. This allows us to understand your situation and explain how we can help. Some specialized matters may require a paid consultation, which will be discussed upfront.',
    'faq.categories': 'Categories',
    'faq.noQuestionsFound': 'No questions found',
    'faq.tryAdjusting': 'Try adjusting your search or browse other categories.',
    'faq.stillHaveQuestions': 'Still Have Questions?',
    'faq.callUs': 'Call Us',
    'faq.callUsDesc': 'Speak directly with our legal experts',
    'faq.emailUs': 'Email Us',
    'faq.emailUsDesc': 'Send us your questions anytime',
    'faq.bookConsultationDesc': 'Book a personalized meeting',
    'faq.popularQuestions': 'Most Popular Questions',
    'faq.howMuchCost': 'How much do legal services cost?',
    'faq.handleNationwide': 'Do you handle cases nationwide?',
    'faq.urgentResponse': 'How quickly can you respond to urgent matters?',
    'faq.whatMakesDifferent': 'What makes your firm different?',

    // Expertise Page
    'expertise.ourExpertise': 'Our Expertise',
    'expertise.practiceAreas': 'Practice Areas',
    'expertise.yearsExperience': 'Years Experience',
    'expertise.casesWon': 'Cases Won',
    'expertise.ourServices': 'Our Services',
    'expertise.keyAchievements': 'Key Achievements',
    'expertise.consultation': 'Consultation',
    'expertise.strategy': 'Strategy',
    'expertise.strategyDesc': 'We develop a tailored legal strategy based on your specific situation',
    'expertise.results': 'Results',
    'expertise.resultsDesc': 'Execute the strategy and achieve the best possible outcome',

    // Contact Page
    'contact.contactUs': 'Contact Us',
    'contact.emergencySupport': 'Emergency Support',
    'contact.free': 'Free',
    'contact.initialConsultation': 'Initial Consultation',
    'contact.sameDay': 'Same Day',
    'contact.responseGuarantee': 'Response Guarantee',
    'contact.sendMessage': 'Send us a Message',
    'contact.address': 'Address',
    'contact.phoneAndFax': 'Phone & Fax',
    'contact.email': 'Email',
    'contact.businessHours': 'Business Hours',
    'contact.businessHoursValue': 'Sunday - Thursday: 9:00 AM - 6:00 PM\nFriday: 9:00 AM - 2:00 PM\nSaturday: Closed',
    'contact.addressValue': 'Legal Plaza, Downtown Cairo\nCairo, Egypt\nP.O. Box 12345',
    'contact.visitOffices': 'Visit Our Offices',
    'contact.interactiveMap': 'Interactive Map',
    'contact.additionalResources': 'Additional Resources',
    'contact.onlineScheduling': 'Online Scheduling',
    'contact.newsletter': 'Newsletter',
    'contact.clientPortal': 'Client Portal',

    // Career Page
    'career.aboutPosition': 'About This Position',
    'career.requirements': 'Requirements',
    'career.keyResponsibilities': 'Key Responsibilities',

    // Form Elements
    'form.priority.normal': 'Normal',
    'form.priority.urgent': 'Urgent (within 48 hours)',
    'form.priority.emergency': 'Emergency (same day)',
    'form.contact.email': 'Email',
    'form.contact.phone': 'Phone',
    'form.contact.text': 'Text Message',
    'form.placeholder.johnSmith': 'John Smith',
    'form.placeholder.johnExample': 'john@example.com',
    'form.placeholder.phoneNumber': '+1 (234) 567-8900',
    'form.placeholder.companyName': 'Company Name',
    'form.placeholder.briefDescription': 'Brief description of your legal matter',
    'form.placeholder.fullName': 'Your full name',
    'form.placeholder.legalNeeds': 'Tell us about your legal needs...',
    'form.placeholder.detailedDescription': 'Please describe your legal matter in detail, including any relevant dates, parties involved, and specific questions you have...',
    'form.searchFAQ': 'Search frequently asked questions...',

    // Navigation Dropdowns
    'nav.dropdown.about.whoWeAre': 'Who We Are',
    'nav.dropdown.about.ourValues': 'Our Values',
    'nav.dropdown.about.ourTeam': 'Our Team',
    'nav.dropdown.expertise.disputeResolution': 'Dispute Resolution',
    'nav.dropdown.expertise.corporateCommercial': 'Corporate & Commercial Law',
    'nav.dropdown.expertise.laborEmployment': 'Labor & Employment',
    'nav.dropdown.expertise.realEstate': 'Real Estate',
    'nav.dropdown.expertise.intellectualProperty': 'Intellectual Property',
    'nav.dropdown.expertise.taxation': 'Taxation',
    'nav.dropdown.expertise.capitalMarket': 'Capital Market & M&A',
    'nav.dropdown.expertise.arbitration': 'Arbitration',
    'nav.dropdown.media.newsHighlights': 'News & Highlights',
    'nav.dropdown.media.photosVideos': 'Photos & Videos',
    'nav.dropdown.library.blog': 'Blog',
    'nav.dropdown.library.publications': 'Publications',

    // About features
    'about.feature1.title': 'Legal Excellence',
    'about.feature1.desc': 'Committed to delivering the highest standard of legal services with integrity and professionalism.',
    'about.feature2.title': 'Client-Centered Approach',
    'about.feature2.desc': 'We put our clients first, understanding their unique needs and providing tailored solutions.',
    'about.feature3.title': 'Proven Track Record',
    'about.feature3.desc': 'Decades of successful cases and satisfied clients across various legal practice areas.',

    // Track record
    'track.title': 'Our Track Record',
    'track.subtitle': 'Numbers that reflect our commitment to excellence and client success',
    'track.clients': 'Satisfied clients across industries',
    'track.outcomes': 'Favorable outcomes for our clients',
    'track.negotiations': 'Successfully negotiated and executed',
    'track.services': 'Providing exceptional legal services',

    // CTA sections
    'cta.joinClients': 'Join Our Satisfied Clients',
    'cta.joinClientsDesc': 'Experience the difference that professional legal representation can make for your business or personal legal matters.',

    // Testimonials
    'testimonials.title': 'What Our Clients Say',
    'testimonials.subtitle': 'Don\'t just take our word for it - hear from our satisfied clients',
    'testimonials.quote1': 'The team\'s deep understanding of corporate law and their strategic approach helped us navigate complex regulatory challenges with confidence.',
    'testimonials.quote2': 'Shehab Law Firm provided exceptional legal guidance during our merger. Their expertise and dedication were instrumental in achieving a successful outcome.',
    'testimonials.quote3': 'Outstanding service and results. They truly understand our business needs and provide practical, effective legal solutions.',
    'testimonials.author1': 'David Rodriguez',
    'testimonials.author2': 'Sarah Johnson',
    'testimonials.author3': 'Michael Chen',
    'testimonials.position1': 'CFO, Financial Partners',
    'testimonials.position2': 'CEO, Global Corp',
    'testimonials.position3': 'Founder, TechStart Inc',

    // News/Articles
    'news.article1.title': 'New Corporate Governance Regulations: What Businesses Need to Know',
    'news.article1.desc': 'Recent changes in corporate governance laws require immediate attention from business leaders. Our analysis of the key implications and compliance requirements.',
    'news.article2.title': 'Real Estate Market Trends and Legal Implications',
    'news.article2.desc': 'Current market dynamics are creating new opportunities and challenges in real estate law. Expert insights on navigating these changes.',
    'news.article3.title': 'Employment Law Updates: Remote Work Policies and Compliance',
    'news.article3.desc': 'The shift to remote work has created new legal considerations for employers. Our comprehensive guide to updating your employment policies.',
    'news.article4.title': 'Intellectual Property Protection in the Digital Age',
    'news.article4.desc': 'As technology evolves, so do the challenges of protecting intellectual property. Learn about the latest strategies and legal frameworks.',
    
    // News placeholders and labels
    'news.readTime': 'min read',
    'news.views': 'views',
    'news.newsletter.placeholder': 'Enter your email',
    'news.newsletter.subscribe': 'Subscribe',
    'news.newsletter.disclaimer': 'No spam, unsubscribe at any time. Privacy policy applies.',
    'news.categories.corporate': 'Corporate Law',
    'news.categories.ip': 'IP Law',
    'news.categories.employment': 'Employment Law',
    'news.categories.realestate': 'Real Estate',

    // Legal Library
    'library.title': 'Legal Library',
    'library.subtitle': 'Access our comprehensive collection of legal insights, research, and educational resources.',
    'library.search.placeholder': 'Search articles and publications...',
    'library.filter.all': 'All',
    'library.filter.blog': 'Blog Articles (6)',
    'library.filter.publications': 'Publications (6)',
    'library.readMore': 'Read More',
    'library.by': 'By',
    'library.subscribe.title': 'Stay Updated',
    'library.subscribe.subtitle': 'Subscribe to receive our latest legal insights, publications, and industry updates directly in your inbox.',
    'library.subscribe.placeholder': 'Enter your email',
    'library.subscribe.button': 'Subscribe',
    'library.subscribe.disclaimer': 'Join 5,000+ legal professionals who trust our insights. Unsubscribe anytime.',

    // Library Articles
    'library.article1.title': 'Understanding the New Data Privacy Regulations',
    'library.article1.desc': 'A comprehensive guide to compliance with updated data privacy laws and their impact on business operations.',
    'library.article1.category': 'Data Privacy',
    'library.article1.tags': 'Compliance, GDPR',
    'library.article1.author': 'Sarah Mitchell',
    'library.article1.readTime': '8 min read',
    'library.article1.views': '3.2k',

    'library.article2.title': 'Corporate Governance Best Practices in 2024',
    'library.article2.desc': 'Essential governance frameworks and compliance strategies for modern corporations navigating complex regulatory environments.',
    'library.article2.category': 'Corporate Law',
    'library.article2.tags': 'Governance, Compliance',
    'library.article2.author': 'Ahmed Shehab',
    'library.article2.readTime': '12 min read',
    'library.article2.views': '2.8k',

    'library.article3.title': 'Employment Law Changes: What HR Teams Need to Know',
    'library.article3.desc': 'Recent updates to employment legislation and practical guidance for implementing compliant HR policies.',
    'library.article3.category': 'Employment Law',
    'library.article3.tags': 'HR Policy, Employment Rights',
    'library.article3.author': 'Maria Rodriguez',
    'library.article3.readTime': '10 min read',
    'library.article3.views': '4.1k',

    'library.article4.title': 'Intellectual Property Protection Strategies',
    'library.article4.desc': 'Effective approaches to safeguarding intellectual property assets in the digital economy.',
    'library.article4.category': 'Intellectual Property',
    'library.article4.tags': 'IP Strategy, Patent Law',
    'library.article4.author': 'David Chen',
    'library.article4.readTime': '15 min read',
    'library.article4.views': '1.9k',

    'library.article5.title': 'Real Estate Investment Legal Considerations',
    'library.article5.desc': 'Key legal factors to consider when making real estate investments, from due diligence to closing.',
    'library.article5.category': 'Real Estate',
    'library.article5.tags': 'Real Estate Investment, Due Diligence',
    'library.article5.author': 'Jennifer Walsh',
    'library.article5.readTime': '9 min read',
    'library.article5.views': '2.3k',

    'library.article6.title': 'Tax Planning Strategies for Businesses',
    'library.article6.desc': 'Effective tax planning approaches to optimize business tax obligations while maintaining compliance.',
    'library.article6.category': 'Tax Law',
    'library.article6.tags': 'Tax Planning, Business Tax',
    'library.article6.author': 'Robert Kim',
    'library.article6.readTime': '11 min read',
    'library.article6.views': '1.7k',

    // Media Center
    'media.title': 'Media Center',
    'media.subtitle': 'Stay informed with our latest news, achievements, and insights from the legal world.',
    'media.newsHighlights': 'News & Highlights',
    'media.photos': 'Photos',
    'media.videos': 'Videos',
    'media.featured': 'Featured',
    'media.recentNews': 'Recent News',
    'media.mediaInquiries': 'Media Inquiries',
    'media.mediaInquiriesDesc': 'For press inquiries, interview requests, or media partnerships, please contact our communications team.',
    'media.contactMediaTeam': 'Contact Media Team',
    'media.downloadPressKit': 'Download Press Kit',

    // Media Articles
    'media.article1.title': 'Shehab Law Firm Wins Major Corporate Litigation Case',
    'media.article1.desc': 'Our litigation team successfully represented a Fortune 500 company in a complex commercial dispute, securing a $50M favorable judgment.',
    'media.article1.category': 'Legal Victory',
    'media.article1.author': 'Legal Team',
    'media.article1.readTime': '2.5k views',
    'media.article1.button': 'Read Full Story',

    'media.article2.title': 'Ahmed Shehab Named "Lawyer of the Year" by Legal Excellence Awards',
    'media.article2.desc': 'Founding Partner Ahmed Shehab received recognition for outstanding achievement in corporate law and client service excellence.',
    'media.article2.category': 'Award',
    'media.article2.author': 'Awards Team',
    'media.article2.readTime': '1.8k views',
    'media.article2.button': 'Read More',

    'media.article3.title': 'New Employment Law Regulations: Firm Provides Expert Analysis',
    'media.article3.desc': 'Our employment law team offers comprehensive guidance on recent regulatory changes affecting workplace policies.',
    'media.article3.category': 'Legal Update',
    'media.article3.author': 'Employment Team',
    'media.article3.readTime': '3.2k views',
    'media.article3.button': 'Read More',

    'media.article4.title': 'Shehab Law Firm Expands Real Estate Practice with New Hires',
    'media.article4.desc': 'Strategic expansion includes three senior associates specializing in commercial real estate and development law.',
    'media.article4.category': 'Firm News',
    'media.article4.author': 'HR Team',
    'media.article4.readTime': '1.1k views',
    'media.article4.button': 'Read More',

    'media.article5.title': 'Record-Breaking M&A Transaction Completed',
    'media.article5.desc': 'Our corporate team facilitated a $200M merger between two industry-leading technology companies.',
    'media.article5.category': 'Transaction',
    'media.article5.author': 'Corporate Team',
    'media.article5.readTime': '2.8k views',
    'media.article5.button': 'Read More',

    'media.article6.title': 'Pro Bono Initiative Helps 100+ Small Businesses',
    'media.article6.desc': 'Our community outreach program provided free legal consultations to local entrepreneurs and small business owners.',
    'media.article6.category': 'Community',
    'media.article6.author': 'Community Team',
    'media.article6.readTime': '950 views',
    'media.article6.button': 'Read More',

    // Career/Join Our Team
    'career.title': 'Join Our Team',
    'career.subtitle': 'Build your legal career with a firm that values excellence, integrity, and professional growth.',
    'career.stats.professionals': 'Legal Professionals',
    'career.stats.years': 'Years in Business',
    'career.stats.satisfaction': 'Employee Satisfaction',
    'career.whyChoose.title': 'Why Choose Shehab Law Firm',
    'career.whyChoose.desc': 'We\'re committed to creating an environment where legal professionals can thrive, grow, and make a meaningful impact.',
    'career.benefits.compensation.title': 'Competitive Compensation',
    'career.benefits.compensation.desc': 'Market-leading salaries with performance-based bonuses and comprehensive benefits package.',
    'career.benefits.development.title': 'Professional Development',
    'career.benefits.development.desc': 'Continuous learning opportunities, CLE credits, conference attendance, and career advancement programs.',
    'career.benefits.collaborative.title': 'Collaborative Environment',
    'career.benefits.collaborative.desc': 'Work alongside experienced attorneys in a supportive, team-oriented culture that values diverse perspectives.',
    'career.benefits.balance.title': 'Work-Life Balance',
    'career.benefits.balance.desc': 'Flexible work arrangements, generous PTO, and wellness programs to support your personal and professional well-being.',
    'career.benefits.recognition.title': 'Recognition & Growth',
    'career.benefits.recognition.desc': 'Clear partnership track, merit-based promotions, and recognition programs that reward excellence and innovation.',
    'career.benefits.health.title': 'Health & Wellness',
    'career.benefits.health.desc': 'Comprehensive health insurance, dental, vision, 401(k) matching, and wellness stipends.',
    'career.opportunities.title': 'Current Opportunities',
    'career.opportunities.desc': 'Explore our current openings and find the perfect opportunity to advance your legal career.',
    'career.job1.title': 'Senior Associate - Corporate Law',
    'career.job1.department': 'Corporate & Commercial',
    'career.job1.location': 'New York, NY',
    'career.job1.type': 'Full-time',
    'career.job1.salary': '$180,000 - $250,000',
    'career.job1.desc': 'We are seeking a senior associate to join our growing corporate practice. The ideal candidate will have extensive experience in M&A transactions, corporate governance, and securities law.',
    'career.job2.title': 'Associate - Litigation',
    'career.job2.department': 'Dispute Resolution',
    'career.job2.location': 'New York, NY',
    'career.job2.type': 'Full-time',
    'career.job2.salary': '$160,000 - $200,000',
    'career.job2.desc': 'Join our award-winning litigation team representing clients in complex commercial disputes, white-collar matters, and regulatory investigations.',
    'career.job3.title': 'Junior Associate - Real Estate',
    'career.job3.department': 'Real Estate',
    'career.job3.location': 'New York, NY',
    'career.job3.type': 'Full-time',
    'career.job3.salary': '$140,000 - $170,000',
    'career.job3.desc': 'Excellent opportunity for a junior associate to join our dynamic real estate practice representing developers, investors, and financial institutions.',
    'career.job4.title': 'Paralegal - Corporate Department',
    'career.job4.department': 'Corporate & Commercial',
    'career.job4.location': 'New York, NY',
    'career.job4.type': 'Full-time',
    'career.job4.salary': '$70,000 - $85,000',
    'career.job4.desc': 'We are looking for an experienced paralegal to support our corporate practice with entity formations, corporate governance, and transactional matters.',
    'career.viewDetails': 'View Details',
    'career.quickApply': 'Quick Apply',
    'career.process.title': 'Application Process',
    'career.process.desc': 'Our streamlined application process is designed to identify the best candidates while respecting your time.',
    'career.process.step1.title': 'Apply Online',
    'career.process.step1.desc': 'Submit your application and resume through our career portal',
    'career.process.step2.title': 'Initial Review',
    'career.process.step2.desc': 'Our HR team reviews your qualifications and experience',
    'career.process.step3.title': 'Interview',
    'career.process.step3.desc': 'Interview with department leaders and team members',
    'career.process.step4.title': 'Welcome',
    'career.process.step4.desc': 'Join our team and begin your career journey with us',
    'career.cta.title': 'Ready to Start Your Career with Us?',
    'career.cta.desc': 'Don\'t see the perfect position? We\'re always interested in hearing from talented legal professionals.',
    'career.cta.sendResume': 'Send Resume',
    'career.cta.contactHR': 'Contact HR',

    // Partners
    'partners.title': 'Partners',
    'partners.subtitle': 'A selection of the organizations that trust us with their legal needs.',
    'partners.industries.title': 'Industries We Serve',
    'partners.industries.desc': 'Our diverse expertise spans across multiple industries, allowing us to provide specialized legal solutions.',
    'partners.cta.title': 'Ready to Join Our Client Family?',
    'partners.cta.desc': 'Experience the difference that professional, dedicated legal representation can make for your organization.',

    // Client Industries
    'partners.industry.technology': 'Technology',
    'partners.industry.healthcare': 'Healthcare',
    'partners.industry.financial': 'Financial Services',
    'partners.industry.manufacturing': 'Manufacturing',
    'partners.industry.realestate': 'Real Estate',
    'partners.industry.energy': 'Energy',
    'partners.industry.retail': 'Retail',
    'partners.industry.construction': 'Construction',
    'partners.industry.media': 'Media & Entertainment',
    'partners.industry.transportation': 'Transportation',
    'partners.industry.education': 'Education',
    'partners.industry.pharmaceuticals': 'Pharmaceuticals',
    'partners.industry.biotechnology': 'Biotechnology',
    'partners.industry.aerospace': 'Aerospace',
    'partners.industry.automotive': 'Automotive',
    'partners.industry.telecommunications': 'Telecommunications',

    // Our Clients - Additional Content
    'clients.stats.activeClients': 'Active Clients',
    'clients.stats.industriesServed': 'Industries Served',
    'clients.stats.satisfaction': 'Client Satisfaction',
    'clients.whoWeServe.title': 'Who We Serve',
    'clients.whoWeServe.desc': 'From global corporations to emerging startups, we provide tailored legal solutions for organizations of all sizes.',
    'clients.fortune500.title': 'Fortune 500 Companies',
    'clients.fortune500.desc': 'Leading multinational corporations trust us with their most complex legal matters.',
    'clients.smb.title': 'Small & Medium Businesses',
    'clients.smb.desc': 'Growing companies rely on our expertise to navigate legal challenges and opportunities.',
    'clients.startups.title': 'Startups & Entrepreneurs',
    'clients.startups.desc': 'Innovation-driven companies choose us for strategic legal guidance and support.',
    'clients.testimonials.title': 'Client Testimonials',
    'clients.testimonials.desc': 'Hear directly from our clients about their experiences working with Shehab Law Firm.',
    'clients.trustedPartners.title': 'Trusted Partners',
    'clients.trustedPartners.desc': 'A selection of the organizations that trust us with their legal needs.',
    'clients.industries.title': 'Industries We Serve',
    'clients.industries.desc': 'Our diverse expertise spans across multiple industries, allowing us to provide specialized legal solutions.',
    'clients.cta.desc': 'Experience the difference that professional, dedicated legal representation can make for your organization.',
    'clients.cta.scheduleConsultation': 'Schedule Consultation',
    'clients.cta.learnMore': 'Learn About Our Services',

    // Client Testimonials
    'clients.testimonial1.quote': 'Shehab Law Firm has been our trusted legal partner for over a decade. Their deep understanding of corporate law and strategic thinking have been invaluable to our success.',
    'clients.testimonial1.author': 'Sarah Johnson',
    'clients.testimonial1.position': 'CEO',
    'clients.testimonial1.company': 'Global Manufacturing Corp',
    'clients.testimonial1.industry': 'Manufacturing',

    'clients.testimonial2.quote': 'The expertise and dedication of the Shehab team helped us navigate a complex merger that transformed our business. Their attention to detail and strategic guidance were exceptional.',
    'clients.testimonial2.author': 'Michael Chen',
    'clients.testimonial2.position': 'General Counsel',
    'clients.testimonial2.company': 'Tech Innovations Inc',
    'clients.testimonial2.industry': 'Technology',

    'clients.testimonial3.quote': 'As a startup, we needed legal counsel who understood our vision and could help us scale efficiently. Shehab Law Firm delivered beyond our expectations.',
    'clients.testimonial3.author': 'Emily Rodriguez',
    'clients.testimonial3.position': 'Founder & CEO',
    'clients.testimonial3.company': 'GreenTech Solutions',
    'clients.testimonial3.industry': 'Clean Energy',

    'clients.testimonial4.quote': 'Their employment law expertise saved us significant costs and helped us build a compliant, productive workplace. Highly recommended for any business.',
    'clients.testimonial4.author': 'David Thompson',
    'clients.testimonial4.position': 'HR Director',
    'clients.testimonial4.company': 'Financial Services Group',
    'clients.testimonial4.industry': 'Financial Services',

    'clients.testimonial5.quote': 'The real estate transaction seemed impossible until Shehab Law Firm got involved. They turned a potential disaster into a successful deal.',
    'clients.testimonial5.author': 'Lisa Wang',
    'clients.testimonial5.position': 'Development Manager',
    'clients.testimonial5.company': 'Premium Properties',
    'clients.testimonial5.industry': 'Real Estate',

    'clients.testimonial6.quote': 'Outstanding intellectual property services. They protected our innovations and helped us build a strong IP portfolio that drives our competitive advantage.',
    'clients.testimonial6.author': 'James Martinez',
    'clients.testimonial6.position': 'CTO',
    'clients.testimonial6.company': 'Biotech Innovations',
    'clients.testimonial6.industry': 'Biotechnology',

    // Form labels
    'form.message': 'Send us a Message',
    'form.name.placeholder': 'Your full name',
    'form.email.placeholder': 'your@email.com',
    'form.phone.placeholder': '+1 (234) 567-8900',
    'form.findOffices': 'Find Our Offices',
    'form.mapNote': 'Interactive map would be integrated here',

    // Footer
    'footer.companyName': 'Shebab Law Firm',
    'footer.tagline': 'Legal Excellence',
    'footer.description': 'An Egyptian law firm bringing together highly qualified legal professionals with diverse local and international backgrounds, serving clients across multiple sectors.',
    'footer.quickLinks': 'Quick Links',
    'footer.practiceAreas': 'Practice Areas',
    'footer.contactInfo': 'Contact Info',
    'footer.copyright': '© 2025 Shehab Law Firm. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.legal': 'Legal Notice',
    
    // Footer navigation links
    'footer.nav.home': 'Home',
    'footer.nav.about': 'About Us',
    'footer.nav.expertise': 'Expertise',
    'footer.nav.clients': 'Clients',
    'footer.nav.career': 'Careers',
    'footer.nav.contact': 'Contact',
    
    // Footer practice areas
    'footer.practice.dispute': 'Dispute Resolution',
    'footer.practice.corporate': 'Corporate & Commercial Law',
    'footer.practice.labor': 'Labor & Employment',
    'footer.practice.realestate': 'Real Estate',
    'footer.practice.intellectual': 'Intellectual Property',
    'footer.practice.taxation': 'Taxation',
};

// Arabic translations
const ar = {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.expertise': 'خبراتنا',
    'nav.clients': 'عملاؤنا',
    'nav.career': 'الوظائف',
    'nav.media': 'الإعلام',
    'nav.library': 'المكتبة',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.contact': 'اتصل بنا',
    
    // Hero
    'hero.title': 'شهاب للمحاماة',
    'hero.title.primary': 'شهاب',
    'hero.title.secondary': '',
    'hero.subtitle': 'شريكك القانوني الموثوق',
    'hero.description': 'مكتب محاماة مصري يجمع بين المتخصصين القانونيين المؤهلين تأهيلاً عالياً ذوي خلفيات محلية ودولية متنوعة، ويقدم حلولاً مبتكرة عبر قطاعات متعددة.',
    'hero.cta': 'تعرف علينا أكثر',
    'hero.cta.secondary': 'جدولة استشارة',
    'hero.stats.years': 'سنوات خبرة',
    'hero.stats.cases': 'قضايا مكسوبة',
    'hero.stats.clients': 'عملاء مخدومون',
    'hero.stats.success': 'معدل النجاح',
    
    // About Preview
    'about.title': 'عن مكتبنا',
    'about.description': 'شهاب مكتب محاماة مصري يجمع بين المهنيين القانونيين المؤهلين تأهيلاً عالياً ذوي خلفيات محلية ودولية متنوعة، ويقدم حلولاً مبتكرة عبر قطاعات متعددة.',
    'about.cta': 'اعرف المزيد',
    'about.p1': 'شهاب مكتب محاماة مصري يجمع بين خبراء قانونيين ذوي كفاءة عالية وخلفيات محلية ودولية متنوعة. تأسس لتقديم خدمات قانونية واستشارية، ونعتمد أساليب مبتكرة لمواكبة التطورات الحكومية والتشريعية.',
    'about.p2': 'ندرك التحديات اليومية التي تواجه الشركات ونسعى لتقديم حلول عملية وسريعة. يعمل محامونا عن قرب مع العملاء لبناء الثقة والالتزام والولاء، وتقديم حلول مبتكرة تدعم النجاح في قطاعات عديدة مثل البنوك، النفط والغاز، الصناعات الثقيلة، الرعاية الصحية، تكنولوجيا المعلومات، الاتصالات، والإعلام.',
    'about.stats.years': 'سنوات',
    'about.stats.cases': 'قضايا',
    
    // Expertise
    'expertise.title': 'مجالات الممارسة',
    'expertise.subtitle': 'خدمات قانونية شاملة عبر مجالات ممارسة متعددة',
    'expertise.learnMore': 'اعرف المزيد',
    'expertise.cta.title': 'هل تحتاج إلى مساعدة قانونية؟',
    'expertise.cta.text': 'فريقنا القانوني ذو الخبرة جاهز لمساعدتك في تجاوز التحديات القانونية المعقدة وتحقيق أفضل النتائج الممكنة.',
    'expertise.cta.schedule': 'احجز استشارة',
    'expertise.cta.contact': 'تواصل مع فريقنا',

    // Expertise areas
    'expertise.dispute.title': 'تسوية المنازعات',
    'expertise.dispute.desc': 'خدمات تقاضي شاملة تغطي القضايا المدنية والتجارية والجنائية مع خبرة في المحاكم المصرية.',
    'expertise.dispute.f1': 'التقاضي المدني والتجاري',
    'expertise.dispute.f2': 'الدفاع الجنائي',
    'expertise.dispute.f3': 'الوسائل البديلة لتسوية المنازعات',

    'expertise.corporate.title': 'القانون التجاري والشركات',
    'expertise.corporate.desc': 'خدمات تأسيس سريعة ومخصصة لجميع أنواع الشركات التجارية داخل مصر وخارجها.',
    'expertise.corporate.f1': 'تأسيس الشركات',
    'expertise.corporate.f2': 'خدمات الأمانة العامة للشركات',
    'expertise.corporate.f3': 'المعاملات التجارية',

    'expertise.employment.title': 'قانون العمل',
    'expertise.employment.desc': 'استشارات متخصصة في قوانين العمل، صياغة العقود، والامتثال للوائح العمل المصرية.',
    'expertise.employment.f1': 'عقود العمل',
    'expertise.employment.f2': 'تطوير سياسات العمل',
    'expertise.employment.f3': 'الامتثال التنظيمي',

    'expertise.realestate.title': 'العقارات',
    'expertise.realestate.desc': 'تسجيل العقارات، اتفاقيات البيع والشراء، واستشارات قانونية للمشروعات التجارية والسكنية والسياحية.',
    'expertise.realestate.f1': 'تسجيل الأملاك',
    'expertise.realestate.f2': 'اتفاقيات البيع والشراء',
    'expertise.realestate.f3': 'التحقق من الملكية',

    'expertise.tmt.title': 'التكنولوجيا والإعلام والاتصالات',
    'expertise.tmt.desc': 'خدمات متخصصة في مجالات التكنولوجيا والإعلام والاتصالات مع التركيز على التراخيص والامتثال التنظيمي.',
    'expertise.tmt.f1': 'تراخيص TMT',
    'expertise.tmt.f2': 'الامتثال التنظيمي',
    'expertise.tmt.f3': 'قانون التجارة الإلكترونية',

    'expertise.tax.title': 'الضرائب',
    'expertise.tax.desc': 'خدمات ضريبية شاملة تشمل حل المنازعات والامتثال والتقارير المالية وفقًا للقانون الضريبي المصري.',
    'expertise.tax.f1': 'تسوية المنازعات الضريبية',
    'expertise.tax.f2': 'الامتثال الضريبي',
    'expertise.tax.f3': 'التقارير المالية',

    'expertise.mna.title': 'أسواق المال والاندماجات والاستحواذات',
    'expertise.mna.desc': 'خبرة في عمليات الاندماج والاستحواذ العامة والخاصة والمشاريع المشتركة وإعادة الهيكلة مع عناية واجبة شاملة.',
    'expertise.mna.f1': 'عمليات الاندماج والاستحواذ',
    'expertise.mna.f2': 'العناية الواجبة',
    'expertise.mna.f3': 'إعادة الهيكلة',

    'expertise.additional.title': 'خدمات إضافية',
    'expertise.additional.desc': 'خدمات الترجمة المعتمدة، التحقيقات في العناية الواجبة، وخدمات دعم الأعمال المتخصصة.',
    'expertise.additional.f1': 'ترجمة معتمدة',
    'expertise.additional.f2': 'العناية الواجبة',
    'expertise.additional.f3': 'تراخيص الأعمال',

    // News
    'news.title': 'آخر الأخبار والرؤى',
    'news.subtitle': 'ابقَ على اطلاع على أحدث التطورات القانونية ورؤى الصناعة والتحليلات المتخصصة من فريقنا القانوني.',
    'news.featured': 'مقال مميز',
    'news.readFull': 'اقرأ المقال كاملًا',
    'news.readMore': 'اقرأ المزيد',
    
    // Statistics
    'stats.years': 'سنوات في العمل',
    'stats.contracts': 'عقود تم إنجازها',
    'stats.cases': 'قضايا محكمة تم كسبها',
    'stats.clients': 'عملاء تم خدمتهم',
    
    // Contact
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'تواصل مع خبرائنا القانونيين',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'عنوان البريد الإلكتروني',
    'contact.form.phone': 'رقم الهاتف',
    'contact.form.message': 'الرسالة',
    'contact.form.submit': 'إرسال الرسالة',

    // الملف التعريفي - نبذة
    'about.profile.title': 'الملف التعريفي – شهاب للمحاماة والاستشارات القانونية',
    'about.profile.aboutTitle': 'عن شهاب للمحاماة والاستشارات القانونية',
    'about.profile.p1': 'شهاب شركة محاماة مصرية تجمع بين خبرات مهنيين قانونيين مؤهلين تأهيلاً عالياً ذوي خلفيات وخبرات محلية ودولية متنوعة.',
    'about.profile.p2': 'تأسست شهاب للمحاماة والاستشارات القانونية بآلية جديدة لمواكبة التطورات في ظل تحديث البيئة التشريعية والقانونية وتعتبر شهاب هي الأكثر انسجاماً مع التحديات التي تواجه الشركات، وبالتالي تسعى جاهدة لإيجاد وتقديم حلول استراتيجية وعملية سريعة. وبذلك يعمل محاموها ومستشاروها عن كثب مع العملاء، لكسب ثقتهم والتزامهم بالتميز تجاههم وإيجاد حلول مبتكرة.',
    'about.profile.p3': 'تعمل الشركة من خلال قطاعات أو أقسام متخصصة تغطي مختلف مجالات ممارسة القانون ، مما يتيح لنا تقديم خدمات قانونية عالية الجودة متسقة بطريقة فعالة. يتعاون فريق العمل لتقديم خدمات قانونية متكاملة إلى العملاء في مختلف القطاعات بما في ذلك، على سبيل المثال لا الحصر، الرياضة، الإنشاءات، المقاولات، النقل و الصناعات الثقيلة، الطاقة، العمليات المصرفية، التمويل، النفط والغاز، الصناعات الثقيلة، المستشفيات، الصناعات الدوائية، تكنولوجيا المعلومات والاتصالات، الإعلام والنقل.',
    'about.profile.p4': 'تستوعب الشركة احتياجات عملائها من خلال الخدمات المتنوعة لتشمل أيضاً على سبيل المثال وليس الحصر، الاستشارات الضريبية وتسوية المنازعات الضريبية، تقديم خدمة الترجمة المعتمدة، إنهاء كافة أعمال التراخيص بمختلف أنواعها، فهي مؤسسة أكثر من مجرد شركة محاماة، كما أن فريق عمل شهاب يعمل بشكل كامل باللغات العربية والإنجليزية.',
    'about.profile.p5': 'إن نجاح الشركة مستمد من خبرة الأعضاء وتفانيهم وخبراتهم المتبادلة مع السلطات القضائية والإدارية والتنظيمية المختصة في مصر.',

    // المهمة / الرؤية / القيم
    'about.mission.title': 'مهمتنـــــا',
    'about.mission.body': 'نلتزم في شهاب بتقديم خدمات قانونية عالية الجودة من خلال مجموعة متميزة من مستشاريها ومحاميها ذوي المهارات العالية، بالإضافة إلى مساعدتهم على تحقيق أعظم النتائج لأعمالهم وذلك من خلال خبرتنا الكبيرة ومعرفتنا بمجالات واستراتيجيات القانون. نحن قادرون على تلبية جميع احتياجات ومتطلبات عملائنا، لذلك نطمح للوصول إلى الثقة الدائمة بعلامتنا التجارية من خلال عملائنا الشركات والأفراد سواء محلياً أو دولياً وذلك باعتبارنا متخصصين في الخدمات القانونية المختلفة.',
    'about.vision.title': 'رؤيتنـــــا',
    'about.vision.body': 'تعد الرؤية الأساسية لشركة شهاب للمحاماة والاستشارات القانونية، هي أن نصبح مستشارين موثوقاً بهم يمكن للعملاء المحليين والدوليين الثقة فيهم والتوجه لإعطاء المشورة القانونية السليمة، بواسطة الوسائل المهنية ومنها حرفية التفاوض وإنهاء المنازعات من خلال التسويات الاتفاقية المقبولة لجميع الأطراف.',
    'about.values.title': 'قيمنـــــا',
    'about.values.body': 'تتمثل القيم الجوهرية لشهاب أننا نتميز بالشفافية تجاه عملائنا من خلال فهمنا المتعمق للقوانين بالإضافة إلى مواكبة التشريعات القانونية الدولية، فإننا نسعى جاهدين لتزويد عملائنا بخدمات قانونية عالية الجودة تتجاوز التوقعات اتكاءً على المصارحة والشفافية والعزم والمصداقية للحفاظ على أعلى مستوى من النزاهة والكفاءة والاستجابة.',

    // خدماتنا - نظرة عامة
    'about.services.title': 'خدمــاتنـــــا',
    'about.services.p1': 'يمكننا في شهاب مساعدتك في عملية البدء في مشروعك ابتداءً من تقديم الاستشارات حول نوع تأسيس شركتك المناسب لك مروراً بإنهاء كافة الإجراءات المتعلقة بالتأمينات الاجتماعية وكافة التراخيص والهيئة العامة للاستثمار والمناطق الحرة والهيئة العامة للرقابة المالية وانتهاءً بصياغة كافة عقود الشركة وتحديد المخاطر المحتملة وكيفية توقيها وأعمال الفحص النافي للجهالة.',
    'about.services.p2': 'شهاب شركة محاماة متكاملة الخدمات ويقع مكتبها في القاهرة، مصر. يقدم مكتب شهاب مجموعة واسعة من الاحتياجات القانونية للشركات الدولية والإقليمية والمحلية وأيضاً الأفراد حيث تمتلك الشركة الخبرة والمعرفة للأعمال التجارية والقانونية والاحتياجات التشغيلية لعملائها. يضمن شهاب مستوى متميزاً للخدمات القانونية عالية الجودة مع توفير طرق إعداد التقارير القابلة للقياس والتي يمكن لعملائنا الاعتماد عليها في أنشطة الأعمال والتخطيط على المدى القصير والمتوسط والطويل.',

    // مجالات الممارسة الأساسية
    'about.practices.title': 'المجالات الرئيسية',
    'about.practices.list.1': 'العقارات والتمويل العقاري',
    'about.practices.list.2': 'الاتصالات وتكنولوجيا المعلومات والإعلام',
    'about.practices.list.3': 'العمل',
    'about.practices.list.4': 'الملكية الفكرية',
    'about.practices.list.5': 'القضــايا',
    'about.practices.list.6': 'سوق المال والدمج والاستحواذ',
    'about.practices.list.7': 'الشركات',

    // أقسام تفصيلية
    'about.section.corporate.title': 'الشركـات (القانون التجاري والشركات)',
    'about.section.corporate.body': 'يقدم شهاب خدمات تأسيس سريعة ومخصصة لجميع أنواع الشركات التجارية والمالية داخل مصر وخارجها، مع خدمات الأمانة العامة ونصائح عامة دقيقة ودعم كامل للاحتياجات القانونية لما قبل التأسيس وبعده، وصياغة ومشورة لمختلف الاتفاقيات التجارية والتراخيص والتمويل.',

    'about.section.mna.title': 'سوق المال والدمــج والاستحواذ',
    'about.section.mna.body': 'تخصص في عمليات الدمج والاستحواذ للاستثمارات العامة والخاصة والمشاريع المشتركة والشركات التجارية وإعادة الهيكلة والتكامل بعد الاستحواذ، مع عناية قانونية واجبة متعمقة وتقارير تقييم للمخاطر وصياغة وتفاوض لجميع الوثائق.',

    'about.section.litigation.title': 'القضــايـا',
    'about.section.litigation.body': 'التعامل مع أنواع مختلفة من الدعاوى القضائية، بما في ذلك الأعمال المصرفية والتمويلية، المعاملات التجارية، البناء، شؤون الشركات، قضايا الاستثمار والاتصالات، وغيرها.',

    'about.section.employment.title': 'العمـــل',
    'about.section.employment.body': 'استشارات قوانين ولوائح العمل، صياغة عقود العمل، ضمان الامتثال للوائح التوظيف، ودعم وضع وتنفيذ السياسات المتعلقة بالعمل.',

    'about.section.tmt.title': 'الاتصالات وتكنولوجيا المعلومات والإعلام',
    'about.section.tmt.body': 'قسم متخصص يقدم خدمات الترخيص والتنظيم والامتثال والخدمات القانونية في مجالات الإعلام والتكنولوجيا والابتكار الريادي والتجارة الإلكترونية.',

    'about.section.realestate.title': 'العقــارات والتمويــل العقــاري',
    'about.section.realestate.body': 'خدمات التسجيل العقاري وصياغة اتفاقيات البيع والشراء واتفاقيات البناء، واستشارات قانونية للمقاولين والمطورين للمشروعات التجارية والسكنية والسياحية، مع التحقق من الملكية والعناية الواجبة بالملكية.',

    // ترانسبيديا - خدمات الترجمة المعتمدة
    'about.transpedia.title': 'ترانسبيديــا لأعمال وخدمات الترجمة المعتمدة',
    'about.transpedia.intro': 'تعتبر ترانسبيديا شركة ذات مسئولية محدودة مسجلة لدى عديد من السفارات الأجنبية، تتخصص في جميع أعمال وخدمات الترجمة العامة والقانونية والمالية والطبية والتقنية وغيرها، بالإضافة الى اعمال كتابة المحتوى وتعمل على خدمة الأفراد والشركات والمؤسسات الحكومية والقانونية بما في ذلك القطاع الخاص أو العام وغيرهم.',
    'about.transpedia.general': 'الترجمـــة العامــة: تقديم خدمات الترجمة العامة في جميع المجالات من الإنجليزية إلى العربية والعكس.',
    'about.transpedia.legal': 'الترجمـــة القانونيــة: توفير مترجم قانوني متخصص للعقود التجارية وأوراق المحكمة والقضايا والمطالبات والإخطارات والتصاريح والمواثيق وغيرها.',
    'about.transpedia.financial': 'الترجمـــة المـاليـــة: ترجمة التقارير المالية، تقارير المراجع الخارجي، الفواتير التجارية، المناقصات، المستحقات المالية، والمراسلات التجارية.',
    'about.transpedia.technical': 'الترجمـــة التقنية والفنيـــة: الترجمة في مجالات التشغيل والصيانة، دليل المستخدم، الكتالوجات التقنية، المناقصات والمزايدات والتقارير التقنية.',
    'about.transpedia.medical': 'الترجمـــة الطبيـــة: جميع الخدمات المتعلقة بالترجمة الطبية من تقارير ونشرات ووثائق ذات طبيعة طبية أو علاجية.',
    'about.transpedia.media': 'الترجمـــة الإعلاميــــة: ترجمة خدمات الصحافة والإعلام من تقارير وتغطية الأحداث والوثائق ذات الطابع الصحفي والإعلامي.',

    // عناصر واجهة المستخدم العامة
    'common.loading': 'جاري التحميل...',
    'common.loadingExperience': 'نحضر تجربتك',
    'common.loadingPage': 'جاري تحميل الصفحة...',
    'common.scrollDown': 'انتقل للأسفل',
    'common.getDirections': 'احصل على الاتجاهات',
    'common.logoAlt': 'شعار مكتب شهاب للمحاماة',
    'common.schedule': 'جدولة',
    'common.scheduleOnline': 'جدولة عبر الإنترنت',
    'common.scheduleConsultation': 'احجز استشارة',
    'common.scheduleNow': 'احجز الآن',
    'common.bookMeeting': 'احجز اجتماعاً مع خبرائنا القانونيين',
    'common.emergencyHelp': 'المساعدة القانونية الطارئة',
    'common.emergencyDesc': 'مساعدة قانونية عاجلة على مدار الساعة',
    'common.callEmergency': 'اتصل بخط الطوارئ',
    'common.clientPortal': 'بوابة العملاء',
    'common.clientPortalDesc': 'الوصول إلى معلومات قضيتك والمستندات',
    'common.loginPortal': 'تسجيل الدخول للبوابة',
    'common.consultation': 'استشارة',
    'common.consultationDesc': 'احجز استشارة أولية مجانية لمناقشة احتياجاتك القانونية',

    // مواقع المكاتب
    'office.main': 'المكتب الرئيسي',
    'office.downtown': 'فرع وسط البلد',
    'office.directions.main': 'احصل على الاتجاهات للمكتب الرئيسي',
    'office.directions.downtown': 'احصل على الاتجاهات لفرع وسط البلد',
    'office.address.main': 'بلازا القانونية، وسط القاهرة\nالقاهرة، مصر\nص.ب 12345',
    'office.emergency': 'خط الطوارئ على مدار الساعة',
    'office.emergencyDesc': 'متاح للعملاء الحاليين والمسائل الجديدة العاجلة التي تتطلب تدخلاً قانونياً فورياً.',
    'office.accessibility': 'يمكن الوصول بالمترو • موقف سيارات متاح',

    // عناصر الصفحة - المحتوى العام
    'page.ourTeam': 'فريقنا',
    'page.awardsRecognition': 'الجوائز والتقدير',
    'page.bestLawFirm2023': 'أفضل مكتب محاماة 2023',
    'page.legalExcellenceAwards': 'جوائز التميز القانوني',
    'page.top50LawFirms': 'أفضل 50 مكتب محاماة',
    'page.nationalLegalDirectory': 'الدليل القانوني الوطني',
    'page.excellenceCorporateLaw': 'التميز في قانون الشركات',
    'page.businessLawJournal': 'مجلة قانون الأعمال',
    'page.photoGalleryComingSoon': 'معرض الصور قريباً...',
    'page.videoContentComingSoon': 'محتوى الفيديو قريباً...',
    'page.messageSent': 'تم إرسال الرسالة!',
    'page.messageSentSuccess': 'تم إرسال الرسالة بنجاح!',
    'page.messageSentThankYou': 'شكراً لتواصلك معنا. سنرد عليك خلال 24 ساعة.',
    'page.emergencyContact': 'جهة الاتصال الطارئ',
    'page.interactiveMapNote': 'سيتم دمج الخريطة التفاعلية هنا',

    // صفحة الأسئلة الشائعة
    'faq.title': 'الأسئلة الشائعة',
    'faq.general.q1': 'ما أنواع الخدمات القانونية التي يقدمها مكتب شهاب للمحاماة؟',
    'faq.general.a1': 'نقدم خدمات قانونية شاملة تشمل قانون الشركات والتجارة، تسوية المنازعات، قانون العمل، قانون العقارات، حماية الملكية الفكرية، الضرائب، أسواق المال والاندماجات والاستحواذات، وخدمات التحكيم. فريقنا ذو الخبرة يتعامل مع المسائل التجارية المعقدة والاحتياجات القانونية الفردية.',
    'faq.general.q2': 'كيف يمكنني جدولة استشارة أولية؟',
    'faq.general.a2': 'يمكنك جدولة استشارة من خلال الاتصال بمكتبنا، أو استخدام نموذج الاتصال عبر الإنترنت، أو إرسال بريد إلكتروني. نحن نقدم عادة استشارة أولية مدتها 30 دقيقة لمناقشة احتياجاتك القانونية وتحديد كيف يمكننا مساعدتك بأفضل شكل.',
    'faq.general.q3': 'هل تقدمون استشارات مجانية؟',
    'faq.general.a3': 'نعم، نقدم استشارات أولية مجانية لمعظم مجالات الممارسة. هذا يتيح لنا فهم وضعك وشرح كيف يمكننا المساعدة. بعض المسائل المتخصصة قد تتطلب استشارة مدفوعة، وسيتم مناقشة ذلك مقدماً.',
    'faq.categories': 'التصنيفات',
    'faq.noQuestionsFound': 'لم يتم العثور على أسئلة',
    'faq.tryAdjusting': 'جرب تعديل بحثك أو تصفح التصنيفات الأخرى.',
    'faq.stillHaveQuestions': 'هل ما زالت لديك أسئلة؟',
    'faq.callUs': 'اتصل بنا',
    'faq.callUsDesc': 'تحدث مباشرة مع خبرائنا القانونيين',
    'faq.emailUs': 'راسلنا بالبريد الإلكتروني',
    'faq.emailUsDesc': 'أرسل لنا أسئلتك في أي وقت',
    'faq.bookConsultationDesc': 'احجز اجتماعاً شخصياً',
    'faq.popularQuestions': 'الأسئلة الأكثر شيوعاً',
    'faq.howMuchCost': 'كم تكلف الخدمات القانونية؟',
    'faq.handleNationwide': 'هل تتعاملون مع القضايا على مستوى الدولة؟',
    'faq.urgentResponse': 'ما مدى سرعة استجابتكم للمسائل العاجلة؟',
    'faq.whatMakesDifferent': 'ما الذي يميز مكتبكم؟',

    // صفحة الخبرات
    'expertise.ourExpertise': 'خبراتنا',
    'expertise.practiceAreas': 'مجالات الممارسة',
    'expertise.yearsExperience': 'سنوات الخبرة',
    'expertise.casesWon': 'القضايا المكسوبة',
    'expertise.ourServices': 'خدماتنا',
    'expertise.keyAchievements': 'الإنجازات الرئيسية',
    'expertise.consultation': 'الاستشارة',
    'expertise.strategy': 'الاستراتيجية',
    'expertise.strategyDesc': 'نضع استراتيجية قانونية مخصصة بناءً على وضعك المحدد',
    'expertise.results': 'النتائج',
    'expertise.resultsDesc': 'تنفيذ الاستراتيجية وتحقيق أفضل النتائج الممكنة',

    // صفحة الاتصال
    'contact.contactUs': 'اتصل بنا',
    'contact.emergencySupport': 'الدعم الطارئ',
    'contact.free': 'مجاني',
    'contact.initialConsultation': 'الاستشارة الأولية',
    'contact.sameDay': 'نفس اليوم',
    'contact.responseGuarantee': 'ضمان الاستجابة',
    'contact.sendMessage': 'أرسل لنا رسالة',
    'contact.address': 'العنوان',
    'contact.phoneAndFax': 'الهاتف والفاكس',
    'contact.email': 'البريد الإلكتروني',
    'contact.businessHours': 'ساعات العمل',
    'contact.businessHoursValue': 'الأحد - الخميس: 9:00 ص - 6:00 م\nالجمعة: 9:00 ص - 2:00 م\nالسبت: مغلق',
    'contact.addressValue': 'بلازا القانونية، وسط القاهرة\nالقاهرة، مصر\nص.ب 12345',
    'contact.visitOffices': 'زر مكاتبنا',
    'contact.interactiveMap': 'الخريطة التفاعلية',
    'contact.additionalResources': 'موارد إضافية',
    'contact.onlineScheduling': 'الجدولة عبر الإنترنت',
    'contact.newsletter': 'النشرة الإخبارية',
    'contact.clientPortal': 'بوابة العملاء',

    // صفحة الوظائف
    'career.aboutPosition': 'حول هذا المنصب',
    'career.requirements': 'المتطلبات',
    'career.keyResponsibilities': 'المسؤوليات الرئيسية',

    // عناصر النماذج
    'form.priority.normal': 'عادي',
    'form.priority.urgent': 'عاجل (خلال 48 ساعة)',
    'form.priority.emergency': 'طارئ (نفس اليوم)',
    'form.contact.email': 'البريد الإلكتروني',
    'form.contact.phone': 'الهاتف',
    'form.contact.text': 'رسالة نصية',
    'form.placeholder.johnSmith': 'أحمد محمد',
    'form.placeholder.johnExample': 'ahmed@example.com',
    'form.placeholder.phoneNumber': '+20 (123) 456-7890',
    'form.placeholder.companyName': 'اسم الشركة',
    'form.placeholder.briefDescription': 'وصف مختصر لمسألتك القانونية',
    'form.placeholder.fullName': 'اسمك الكامل',
    'form.placeholder.legalNeeds': 'أخبرنا عن احتياجاتك القانونية...',
    'form.placeholder.detailedDescription': 'يرجى وصف مسألتك القانونية بالتفصيل، بما في ذلك أي تواريخ ذات صلة والأطراف المعنية والأسئلة المحددة لديك...',
    'form.searchFAQ': 'البحث في الأسئلة الشائعة...',

    // قوائم التنقل المنسدلة
    'nav.dropdown.about.whoWeAre': 'من نحن',
    'nav.dropdown.about.ourValues': 'قيمنا',
    'nav.dropdown.about.ourTeam': 'فريقنا',
    'nav.dropdown.expertise.disputeResolution': 'فض المنازعات',
    'nav.dropdown.expertise.corporateCommercial': 'قانون الشركات والتجارة',
    'nav.dropdown.expertise.laborEmployment': 'العمل والتوظيف',
    'nav.dropdown.expertise.realEstate': 'العقارات',
    'nav.dropdown.expertise.intellectualProperty': 'الملكية الفكرية',
    'nav.dropdown.expertise.taxation': 'الضرائب',
    'nav.dropdown.expertise.capitalMarket': 'سوق المال والاندماج والاستحواذ',
    'nav.dropdown.expertise.arbitration': 'التحكيم',
    'nav.dropdown.media.newsHighlights': 'الأخبار والأحداث البارزة',
    'nav.dropdown.media.photosVideos': 'الصور والفيديوهات',
    'nav.dropdown.library.blog': 'المدونة',
    'nav.dropdown.library.publications': 'المنشورات',

    // ميزات الشركة
    'about.feature1.title': 'التميز القانوني',
    'about.feature1.desc': 'ملتزمون بتقديم أعلى معايير الخدمات القانونية بنزاهة ومهنية.',
    'about.feature2.title': 'نهج يركز على العميل',
    'about.feature2.desc': 'نضع عملاءنا في المقدمة، ونفهم احتياجاتهم الفريدة ونقدم حلولاً مخصصة.',
    'about.feature3.title': 'سجل حافل مثبت',
    'about.feature3.desc': 'عقود من القضايا الناجحة والعملاء الراضين عبر مختلف مجالات الممارسة القانونية.',

    // السجل الحافل
    'track.title': 'سجلنا الحافل',
    'track.subtitle': 'أرقام تعكس التزامنا بالتميز ونجاح العملاء',
    'track.clients': 'عملاء راضون عبر الصناعات',
    'track.outcomes': 'نتائج مواتية لعملائنا',
    'track.negotiations': 'تفاوض وتنفيذ ناجح',
    'track.services': 'تقديم خدمات قانونية استثنائية',

    // العملاء
    'clients.title': 'عملاؤنا الكرام',
    'clients.subtitle': 'موثوقون من قبل المنظمات الرائدة عبر مختلف الصناعات',
    'clients.cta.title': 'انضم إلى عملائنا الراضين',
    'clients.cta.description': 'اختبر الفرق الذي يمكن أن يحدثه التمثيل القانوني المهني لأعمالك أو مسائلك القانونية الشخصية.',
    'clients.cta.become': 'كن عميلاً',
    'clients.cta.studies': 'عرض دراسات الحالة',

    // أقسام الدعوة للعمل
    'cta.joinClients': 'انضم إلى عملائنا الراضين',
    'cta.joinClientsDesc': 'اختبر الفرق الذي يمكن أن يحدثه التمثيل القانوني المهني لأعمالك أو مسائلك القانونية الشخصية.',

    // الشهادات
    'testimonials.title': 'ما يقوله عملاؤنا',
    'testimonials.subtitle': 'لا تأخذ كلامنا فقط - استمع إلى عملائنا الراضين',
    'testimonials.quote1': 'الفهم العميق لفريق العمل لقانون الشركات ونهجهم الاستراتيجي ساعدنا في التنقل عبر التحديات التنظيمية المعقدة بثقة.',
    'testimonials.quote2': 'قدم مكتب شهاب للمحاماة إرشاداً قانونياً استثنائياً خلال عملية الاندماج. كانت خبرتهم وتفانيهم حاسمة في تحقيق نتيجة ناجحة.',
    'testimonials.quote3': 'خدمة ونتائج متميزة. إنهم يفهمون حقاً احتياجات أعمالنا ويقدمون حلولاً قانونية عملية وفعالة.',
    'testimonials.author1': 'ديفيد رودريغيز',
    'testimonials.author2': 'سارة جونسون',
    'testimonials.author3': 'مايكل تشن',
    'testimonials.position1': 'الرئيس المالي، شركاء ماليون',
    'testimonials.position2': 'الرئيس التنفيذي، شركة جلوبال',
    'testimonials.position3': 'المؤسس، تيك ستارت',

    // الأخبار/المقالات
    'news.article1.title': 'لوائح الحوكمة المؤسسية الجديدة: ما تحتاج الشركات لمعرفته',
    'news.article1.desc': 'التغييرات الأخيرة في قوانين الحوكمة المؤسسية تتطلب اهتماماً فورياً من قادة الأعمال. تحليلنا للآثار الرئيسية ومتطلبات الامتثال.',
    'news.article2.title': 'اتجاهات السوق العقاري والآثار القانونية',
    'news.article2.desc': 'ديناميكيات السوق الحالية تخلق فرصاً وتحديات جديدة في قانون العقارات. رؤى الخبراء حول التنقل في هذه التغييرات.',
    'news.article3.title': 'تحديثات قانون العمل: سياسات العمل عن بعد والامتثال',
    'news.article3.desc': 'التحول إلى العمل عن بعد خلق اعتبارات قانونية جديدة لأصحاب العمل. دليلنا الشامل لتحديث سياسات التوظيف الخاصة بك.',
    'news.article4.title': 'حماية الملكية الفكرية في العصر الرقمي',
    'news.article4.desc': 'مع تطور التكنولوجيا، تتطور أيضاً تحديات حماية الملكية الفكرية. تعرف على أحدث الاستراتيجيات والأطر القانونية.',
    
    // تسميات ومكانس الأخبار
    'news.readTime': 'دقائق قراءة',
    'news.views': 'مشاهدات',
    'news.newsletter.placeholder': 'أدخل بريدك الإلكتروني',
    'news.newsletter.subscribe': 'اشترك',
    'news.newsletter.disclaimer': 'لا بريد مزعج، يمكنك إلغاء الاشتراك في أي وقت. تنطبق سياسة الخصوصية.',
    'news.categories.corporate': 'قانون الشركات',
    'news.categories.ip': 'قانون الملكية الفكرية',
    'news.categories.employment': 'قانون العمل',
    'news.categories.realestate': 'العقارات',

    // المكتبة القانونية
    'library.title': 'المكتبة القانونية',
    'library.subtitle': 'الوصول إلى مجموعتنا الشاملة من الرؤى القانونية والأبحاث والموارد التعليمية.',
    'library.search.placeholder': 'البحث في المقالات والمنشورات...',
    'library.filter.all': 'الكل',
    'library.filter.blog': 'مقالات المدونة (6)',
    'library.filter.publications': 'المنشورات (6)',
    'library.readMore': 'اقرأ المزيد',
    'library.by': 'بواسطة',
    'library.subscribe.title': 'ابق على اطلاع',
    'library.subscribe.subtitle': 'اشترك لتلقي أحدث رؤانا القانونية والمنشورات وتحديثات الصناعة مباشرة في صندوق الوارد الخاص بك.',
    'library.subscribe.placeholder': 'أدخل بريدك الإلكتروني',
    'library.subscribe.button': 'اشترك',
    'library.subscribe.disclaimer': 'انضم إلى 5,000+ من المهنيين القانونيين الذين يثقون في رؤانا. يمكنك إلغاء الاشتراك في أي وقت.',

    // مقالات المكتبة
    'library.article1.title': 'فهم لوائح الخصوصية الجديدة',
    'library.article1.desc': 'دليل شامل للامتثال لقوانين الخصوصية المحدثة وتأثيرها على عمليات الأعمال.',
    'library.article1.category': 'خصوصية البيانات',
    'library.article1.tags': 'الامتثال، GDPR',
    'library.article1.author': 'سارة ميتشيل',
    'library.article1.readTime': '8 دقائق قراءة',
    'library.article1.views': '3.2k',

    'library.article2.title': 'أفضل ممارسات الحوكمة المؤسسية في 2024',
    'library.article2.desc': 'أطر الحوكمة الأساسية واستراتيجيات الامتثال للشركات الحديثة التي تتنقل في البيئات التنظيمية المعقدة.',
    'library.article2.category': 'قانون الشركات',
    'library.article2.tags': 'الحوكمة، الامتثال',
    'library.article2.author': 'أحمد شهاب',
    'library.article2.readTime': '12 دقيقة قراءة',
    'library.article2.views': '2.8k',

    'library.article3.title': 'تغييرات قانون العمل: ما تحتاج فرق الموارد البشرية لمعرفته',
    'library.article3.desc': 'التحديثات الأخيرة على تشريعات العمل والإرشادات العملية لتنفيذ سياسات الموارد البشرية الممتثلة.',
    'library.article3.category': 'قانون العمل',
    'library.article3.tags': 'سياسة الموارد البشرية، حقوق العمل',
    'library.article3.author': 'ماريا رودريغيز',
    'library.article3.readTime': '10 دقائق قراءة',
    'library.article3.views': '4.1k',

    'library.article4.title': 'استراتيجيات حماية الملكية الفكرية',
    'library.article4.desc': 'النهج الفعالة لحماية أصول الملكية الفكرية في الاقتصاد الرقمي.',
    'library.article4.category': 'الملكية الفكرية',
    'library.article4.tags': 'استراتيجية الملكية الفكرية، قانون البراءات',
    'library.article4.author': 'ديفيد تشن',
    'library.article4.readTime': '15 دقيقة قراءة',
    'library.article4.views': '1.9k',

    'library.article5.title': 'الاعتبارات القانونية لاستثمارات العقارات',
    'library.article5.desc': 'العوامل القانونية الرئيسية التي يجب مراعاتها عند الاستثمار في العقارات، من العناية الواجبة إلى الإغلاق.',
    'library.article5.category': 'العقارات',
    'library.article5.tags': 'استثمار العقارات، العناية الواجبة',
    'library.article5.author': 'جينيفر والش',
    'library.article5.readTime': '9 دقائق قراءة',
    'library.article5.views': '2.3k',

    'library.article6.title': 'استراتيجيات التخطيط الضريبي للشركات',
    'library.article6.desc': 'نهج التخطيط الضريبي الفعالة لتحسين الالتزامات الضريبية للشركات مع الحفاظ على الامتثال.',
    'library.article6.category': 'قانون الضرائب',
    'library.article6.tags': 'التخطيط الضريبي، ضريبة الأعمال',
    'library.article6.author': 'روبرت كيم',
    'library.article6.readTime': '11 دقيقة قراءة',
    'library.article6.views': '1.7k',

    // مركز الإعلام
    'media.title': 'مركز الإعلام',
    'media.subtitle': 'ابق على اطلاع بأحدث الأخبار والإنجازات والرؤى من العالم القانوني.',
    'media.newsHighlights': 'الأخبار والمميزات',
    'media.photos': 'الصور',
    'media.videos': 'الفيديوهات',
    'media.featured': 'مميز',
    'media.recentNews': 'الأخبار الحديثة',
    'media.mediaInquiries': 'استفسارات إعلامية',
    'media.mediaInquiriesDesc': 'للاستفسارات الصحفية أو طلبات المقابلات أو الشراكات الإعلامية، يرجى الاتصال بفريق الاتصالات لدينا.',
    'media.contactMediaTeam': 'اتصل بفريق الإعلام',
    'media.downloadPressKit': 'تحميل حقيبة الصحافة',

    // مقالات الإعلام
    'media.article1.title': 'مكتب شهاب للمحاماة يفوز بقضية دعوى شركات كبرى',
    'media.article1.desc': 'نجح فريق التقاضي لدينا في تمثيل شركة من فورتشن 500 في نزاع تجاري معقد، وحقق حكماً لصالحها بقيمة 50 مليون دولار.',
    'media.article1.category': 'انتصار قانوني',
    'media.article1.author': 'الفريق القانوني',
    'media.article1.readTime': '2.5k مشاهدة',
    'media.article1.button': 'اقرأ القصة كاملة',

    'media.article2.title': 'أحمد شهاب يُسمى "محامي العام" من جوائز التميز القانوني',
    'media.article2.desc': 'تلقى الشريك المؤسس أحمد شهاب اعترافاً لإنجازه المتميز في قانون الشركات وتميز خدمة العملاء.',
    'media.article2.category': 'جائزة',
    'media.article2.author': 'فريق الجوائز',
    'media.article2.readTime': '1.8k مشاهدة',
    'media.article2.button': 'اقرأ المزيد',

    'media.article3.title': 'لوائح قانون العمل الجديدة: المكتب يقدم تحليلاً خبيراً',
    'media.article3.desc': 'يقدم فريق قانون العمل لدينا إرشادات شاملة حول التغييرات التنظيمية الأخيرة التي تؤثر على سياسات مكان العمل.',
    'media.article3.category': 'تحديث قانوني',
    'media.article3.author': 'فريق العمل',
    'media.article3.readTime': '3.2k مشاهدة',
    'media.article3.button': 'اقرأ المزيد',

    'media.article4.title': 'مكتب شهاب للمحاماة يوسع ممارسة العقارات بتوظيفات جديدة',
    'media.article4.desc': 'يشمل التوسع الاستراتيجي ثلاثة مساعدين كبار متخصصين في قانون العقارات التجارية وقانون التطوير.',
    'media.article4.category': 'أخبار المكتب',
    'media.article4.author': 'فريق الموارد البشرية',
    'media.article4.readTime': '1.1k مشاهدة',
    'media.article4.button': 'اقرأ المزيد',

    'media.article5.title': 'إتمام صفقة اندماج واستحواذ قياسية',
    'media.article5.desc': 'ساعد فريق الشركات لدينا في تسهيل اندماج بقيمة 200 مليون دولار بين شركتين رائدتين في التكنولوجيا.',
    'media.article5.category': 'صفقة',
    'media.article5.author': 'فريق الشركات',
    'media.article5.readTime': '2.8k مشاهدة',
    'media.article5.button': 'اقرأ المزيد',

    'media.article6.title': 'مبادرة العمل التطوعي تساعد أكثر من 100 شركة صغيرة',
    'media.article6.desc': 'قدم برنامج التوعية المجتمعية لدينا استشارات قانونية مجانية لأصحاب المشاريع المحليين وأصحاب الشركات الصغيرة.',
    'media.article6.category': 'مجتمع',
    'media.article6.author': 'فريق المجتمع',
    'media.article6.readTime': '950 مشاهدة',
    'media.article6.button': 'اقرأ المزيد',

    // الانضمام لفريقنا
    'career.title': 'انضم لفريقنا',
    'career.subtitle': 'ابني مسيرتك القانونية مع مكتب يقدر التميز والنزاهة والنمو المهني.',
    'career.stats.professionals': 'محترف قانوني',
    'career.stats.years': 'سنة في العمل',
    'career.stats.satisfaction': 'رضا الموظفين',
    'career.whyChoose.title': 'لماذا تختار مكتب شهاب للمحاماة',
    'career.whyChoose.desc': 'نحن ملتزمون بخلق بيئة يمكن للمهنيين القانونيين فيها الازدهار والنمو وإحداث تأثير ذي معنى.',
    'career.benefits.compensation.title': 'تعويضات تنافسية',
    'career.benefits.compensation.desc': 'رواتب رائدة في السوق مع مكافآت قائمة على الأداء وحزمة مزايا شاملة.',
    'career.benefits.development.title': 'التطوير المهني',
    'career.benefits.development.desc': 'فرص التعلم المستمر، اعتمادات التعليم القانوني المستمر، حضور المؤتمرات، وبرامج التقدم الوظيفي.',
    'career.benefits.collaborative.title': 'بيئة تعاونية',
    'career.benefits.collaborative.desc': 'العمل جنباً إلى جنب مع محامين ذوي خبرة في ثقافة داعمة تركز على الفريق وتقدر وجهات النظر المتنوعة.',
    'career.benefits.balance.title': 'التوازن بين العمل والحياة',
    'career.benefits.balance.desc': 'ترتيبات عمل مرنة، إجازة سخية، وبرامج الصحة لدعم رفاهيتك الشخصية والمهنية.',
    'career.benefits.recognition.title': 'التقدير والنمو',
    'career.benefits.recognition.desc': 'مسار واضح للشراكة، ترقيات قائمة على الجدارة، وبرامج تقدير تكافئ التميز والابتكار.',
    'career.benefits.health.title': 'الصحة والعافية',
    'career.benefits.health.desc': 'تأمين صحي شامل، طب الأسنان، البصر، مطابقة 401(k)، ومخصصات العافية.',
    'career.opportunities.title': 'الفرص الحالية',
    'career.opportunities.desc': 'استكشف فرصنا الحالية واعثر على الفرصة المثالية لتطوير مسيرتك القانونية.',
    'career.job1.title': 'محامي أول - قانون الشركات',
    'career.job1.department': 'الشركات والتجارة',
    'career.job1.location': 'نيويورك، نيويورك',
    'career.job1.type': 'دوام كامل',
    'career.job1.salary': '$180,000 - $250,000',
    'career.job1.desc': 'نبحث عن محامي أول للانضمام إلى ممارستنا المتنامية في قانون الشركات. المرشح المثالي سيكون لديه خبرة واسعة في معاملات الاندماج والاستحواذ، والحوكمة المؤسسية، وقانون الأوراق المالية.',
    'career.job2.title': 'محامي - التقاضي',
    'career.job2.department': 'حل النزاعات',
    'career.job2.location': 'نيويورك، نيويورك',
    'career.job2.type': 'دوام كامل',
    'career.job2.salary': '$160,000 - $200,000',
    'career.job2.desc': 'انضم إلى فريق التقاضي الحائز على الجوائز الذي يمثل العملاء في النزاعات التجارية المعقدة، وقضايا ذوي الياقات البيضاء، والتحقيقات التنظيمية.',
    'career.job3.title': 'محامي مبتدئ - العقارات',
    'career.job3.department': 'العقارات',
    'career.job3.location': 'نيويورك، نيويورك',
    'career.job3.type': 'دوام كامل',
    'career.job3.salary': '$140,000 - $170,000',
    'career.job3.desc': 'فرصة ممتازة لمحامي مبتدئ للانضمام إلى ممارستنا الديناميكية في العقارات التي تمثل المطورين والمستثمرين والمؤسسات المالية.',
    'career.job4.title': 'مساعد قانوني - قسم الشركات',
    'career.job4.department': 'الشركات والتجارة',
    'career.job4.location': 'نيويورك، نيويورك',
    'career.job4.type': 'دوام كامل',
    'career.job4.salary': '$70,000 - $85,000',
    'career.job4.desc': 'نبحث عن مساعد قانوني ذي خبرة لدعم ممارستنا في الشركات بتكوين الكيانات، والحوكمة المؤسسية، والمسائل المعاملية.',
    'career.viewDetails': 'عرض التفاصيل',
    'career.quickApply': 'تطبيق سريع',
    'career.process.title': 'عملية التقديم',
    'career.process.desc': 'عملية التقديم المبسطة لدينا مصممة لتحديد أفضل المرشحين مع احترام وقتك.',
    'career.process.step1.title': 'تقدم عبر الإنترنت',
    'career.process.step1.desc': 'أرسل طلبك وسيرتك الذاتية من خلال بوابة الوظائف لدينا',
    'career.process.step2.title': 'المراجعة الأولية',
    'career.process.step2.desc': 'فريق الموارد البشرية لدينا يراجع مؤهلاتك وخبرتك',
    'career.process.step3.title': 'المقابلة',
    'career.process.step3.desc': 'مقابلة مع قادة الأقسام وأعضاء الفريق',
    'career.process.step4.title': 'مرحباً بك',
    'career.process.step4.desc': 'انضم إلى فريقنا وابدأ رحلة مسيرتك المهنية معنا',
    'career.cta.title': 'مستعد لبدء مسيرتك المهنية معنا؟',
    'career.cta.desc': 'لا تجد المنصب المثالي؟ نحن مهتمون دائماً بالاستماع من المهنيين القانونيين الموهوبين.',
    'career.cta.sendResume': 'أرسل السيرة الذاتية',
    'career.cta.contactHR': 'اتصل بالموارد البشرية',

    // الشركاء
    'partners.title': 'الشركاء',
    'partners.subtitle': 'مجموعة مختارة من المنظمات التي تثق فينا لتلبية احتياجاتها القانونية.',
    'partners.industries.title': 'القطاعات التي نخدمها',
    'partners.industries.desc': 'خبرتنا المتنوعة تمتد عبر قطاعات متعددة، مما يتيح لنا تقديم حلول قانونية متخصصة.',
    'partners.cta.title': 'مستعد للانضمام إلى عائلة عملائنا؟',
    'partners.cta.desc': 'اختبر الفرق الذي يمكن أن يحدثه التمثيل القانوني المهني والمتفاني لمنظمتك.',

    // قطاعات العملاء
    'partners.industry.technology': 'التكنولوجيا',
    'partners.industry.healthcare': 'الرعاية الصحية',
    'partners.industry.financial': 'الخدمات المالية',
    'partners.industry.manufacturing': 'التصنيع',
    'partners.industry.realestate': 'العقارات',
    'partners.industry.energy': 'الطاقة',
    'partners.industry.retail': 'التجارة بالتجزئة',
    'partners.industry.construction': 'البناء',
    'partners.industry.media': 'الإعلام والترفيه',
    'partners.industry.transportation': 'النقل',
    'partners.industry.education': 'التعليم',
    'partners.industry.pharmaceuticals': 'الأدوية',
    'partners.industry.biotechnology': 'التكنولوجيا الحيوية',
    'partners.industry.aerospace': 'الطيران',
    'partners.industry.automotive': 'السيارات',
    'partners.industry.telecommunications': 'الاتصالات',

    // عملاؤنا - محتوى إضافي
    'clients.stats.activeClients': 'عميل نشط',
    'clients.stats.industriesServed': 'قطاع نخدمه',
    'clients.stats.satisfaction': 'رضا العملاء',
    'clients.whoWeServe.title': 'من نخدم',
    'clients.whoWeServe.desc': 'من الشركات العالمية إلى الشركات الناشئة الناشئة، نقدم حلولاً قانونية مخصصة للمنظمات من جميع الأحجام.',
    'clients.fortune500.title': 'شركات فورتشن 500',
    'clients.fortune500.desc': 'تثق فينا الشركات متعددة الجنسيات الرائدة في أكثر مسائلها القانونية تعقيداً.',
    'clients.smb.title': 'الشركات الصغيرة والمتوسطة',
    'clients.smb.desc': 'تعتمد الشركات النامية على خبرتنا للتنقل في التحديات والفرص القانونية.',
    'clients.startups.title': 'الشركات الناشئة ورجال الأعمال',
    'clients.startups.desc': 'تختارنا الشركات المدفوعة بالابتكار للحصول على الإرشاد القانوني الاستراتيجي والدعم.',
    'clients.testimonials.title': 'شهادات العملاء',
    'clients.testimonials.desc': 'استمع مباشرة من عملائنا حول تجاربهم في العمل مع مكتب شهاب للمحاماة.',
    'clients.trustedPartners.title': 'الشركاء الموثوقون',
    'clients.trustedPartners.desc': 'مجموعة مختارة من المنظمات التي تثق فينا لتلبية احتياجاتها القانونية.',
    'clients.industries.title': 'القطاعات التي نخدمها',
    'clients.industries.desc': 'خبرتنا المتنوعة تمتد عبر قطاعات متعددة، مما يتيح لنا تقديم حلول قانونية متخصصة.',
    'clients.cta.desc': 'اختبر الفرق الذي يمكن أن يحدثه التمثيل القانوني المهني والمتفاني لمنظمتك.',
    'clients.cta.scheduleConsultation': 'احجز استشارة',
    'clients.cta.learnMore': 'تعرف على خدماتنا',

    // شهادات العملاء
    'clients.testimonial1.quote': 'كان مكتب شهاب للمحاماة شريكنا القانوني الموثوق لأكثر من عقد من الزمان. فهمهم العميق لقانون الشركات والتفكير الاستراتيجي كان لا يقدر بثمن لنجاحنا.',
    'clients.testimonial1.author': 'سارة جونسون',
    'clients.testimonial1.position': 'الرئيس التنفيذي',
    'clients.testimonial1.company': 'شركة التصنيع العالمية',
    'clients.testimonial1.industry': 'التصنيع',

    'clients.testimonial2.quote': 'ساعدت خبرة وتفاني فريق شهاب في التنقل في اندماج معقد غير شكل أعمالنا. كانت انتباههم للتفاصيل والإرشاد الاستراتيجي استثنائيين.',
    'clients.testimonial2.author': 'مايكل تشن',
    'clients.testimonial2.position': 'المستشار العام',
    'clients.testimonial2.company': 'شركة الابتكارات التقنية',
    'clients.testimonial2.industry': 'التكنولوجيا',

    'clients.testimonial3.quote': 'كشركة ناشئة، احتجنا إلى مستشار قانوني يفهم رؤيتنا ويمكنه مساعدتنا على التوسع بكفاءة. قدم مكتب شهاب للمحاماة ما يتجاوز توقعاتنا.',
    'clients.testimonial3.author': 'إيميلي رودريغيز',
    'clients.testimonial3.position': 'المؤسس والرئيس التنفيذي',
    'clients.testimonial3.company': 'حلول التكنولوجيا الخضراء',
    'clients.testimonial3.industry': 'الطاقة النظيفة',

    'clients.testimonial4.quote': 'وفرت خبرتهم في قانون العمل تكاليف كبيرة وساعدتنا على بناء مكان عمل متوافق ومنتج. موصى به بشدة لأي عمل.',
    'clients.testimonial4.author': 'ديفيد طومسون',
    'clients.testimonial4.position': 'مدير الموارد البشرية',
    'clients.testimonial4.company': 'مجموعة الخدمات المالية',
    'clients.testimonial4.industry': 'الخدمات المالية',

    'clients.testimonial5.quote': 'بدت صفقة العقارات مستحيلة حتى تدخل مكتب شهاب للمحاماة. حولوا كارثة محتملة إلى صفقة ناجحة.',
    'clients.testimonial5.author': 'ليزا وانغ',
    'clients.testimonial5.position': 'مدير التطوير',
    'clients.testimonial5.company': 'العقارات المتميزة',
    'clients.testimonial5.industry': 'العقارات',

    'clients.testimonial6.quote': 'خدمات متميزة في الملكية الفكرية. حموا ابتكاراتنا وساعدونا على بناء محفظة قوية من الملكية الفكرية تدفع ميزتنا التنافسية.',
    'clients.testimonial6.author': 'جيمس مارتينيز',
    'clients.testimonial6.position': 'الرئيس التقني',
    'clients.testimonial6.company': 'ابتكارات التكنولوجيا الحيوية',
    'clients.testimonial6.industry': 'التكنولوجيا الحيوية',

    // تسميات النموذج
    'form.message': 'أرسل لنا رسالة',
    'form.name.placeholder': 'اسمك الكامل',
    'form.email.placeholder': 'your@email.com',
    'form.phone.placeholder': '+1 (234) 567-8900',
    'form.findOffices': 'ابحث عن مكاتبنا',
    'form.mapNote': 'سيتم دمج خريطة تفاعلية هنا',

    // التذييل
    'footer.companyName': 'شهاب للمحاماة',
    'footer.tagline': 'التميز القانوني',
    'footer.description': 'مكتب محاماة مصري يجمع بين المتخصصين القانونيين المؤهلين تأهيلاً عالياً ذوي خلفيات محلية ودولية متنوعة، يخدم العملاء عبر قطاعات متعددة.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.practiceAreas': 'مجالات الممارسة',
    'footer.contactInfo': 'معلومات الاتصال',
    'footer.copyright': '© 2025 مكتب شهاب للمحاماة. جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.legal': 'إشعار قانوني',
    
    // روابط التنقل في التذييل
    'footer.nav.home': 'الرئيسية',
    'footer.nav.about': 'من نحن',
    'footer.nav.expertise': 'خبراتنا',
    'footer.nav.clients': 'عملاؤنا',
    'footer.nav.career': 'الوظائف',
    'footer.nav.contact': 'اتصل بنا',
    
    // مجالات الممارسة في التذييل
    'footer.practice.dispute': 'تسوية المنازعات',
    'footer.practice.corporate': 'القانون التجاري والشركات',
    'footer.practice.labor': 'قانون العمل',
    'footer.practice.realestate': 'العقارات',
    'footer.practice.intellectual': 'الملكية الفكرية',
    'footer.practice.taxation': 'الضرائب',
};

// Combined translations object
const translations: Record<'en' | 'ar', Record<string, string>> = {
  en,
  ar
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'ar'>('en');
  const isRTL = language === 'ar';

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  React.useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};